// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql"
)

type Task struct {
	ID          int64
	Title       sql.NullString
	Description sql.NullString
	Status      sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	UserID      sql.NullInt64
}

type User struct {
	ID           int64
	Username     sql.NullString
	PasswordHash sql.NullString
	Email        sql.NullString
	CreatedAt    sql.NullTime
}
