// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql"
	"time"
)

type Task struct {
	ID          int64
	Title       string
	Description string
	Status      string
	CreatedAt   time.Time
	UpdatedAt   sql.NullTime
	UserID      int64
}

type User struct {
	ID           int64
	Username     string
	PasswordHash string
	Email        sql.NullString
	CreatedAt    time.Time
}
